name: style_dart
description: A Backend framework for Dart. Style is a modular,easy-to-understand framework and it have flutter style syntax.
version: 1.0.2+8
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style/
repository: https://github.com/Mehmetyaz/style

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.3.0
  queue: ^3.1.0+1
  json_schema2: ^2.0.0+4
  style_cron_job: ^1.0.4+2
  meta: ^1.7.0

dev_dependencies:
  cryptography: ^2.0.5
  effective_dart: ^1.3.2
  test: ^1.19.4
  style_test: ^1.0.0+2